@startuml
'https://plantuml.com/use-case-diagram
note left of Start: All possible interactions with system
left to right direction
:Start:-l-> (Show book info)
:Start:-l-> (Search for book)
:Start:-l-> (Add book)
:Start:-l-> (Remove book)
:Start:-u-> (Change book information)
:Start:-u-> (Search for author)
:Start:-u-> (Search for category)
:Start:-u-> (Search for subcategory)
:Start:-r-> (Add subcategory)
:Start:-r-> (Remove subcategory)
:Start:-r-> (Change subcategory)
:Start:-r-> (Assign category to parent-category)
:Start:-d-> (Move category to other parent-category)
:Start:-d-> (Show all subcategories)
:Start:-d-> (Read library from file)
:Start:-d-> (Save library to file)

@enduml
